### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by matthdsm** [shyamrallapalli/biojs-vcf#7]
Hi,

I'm looking for a js module that can read and query compressed and indexed vcf files from a remote location (e.g. S3-buckets). I was wondering if this is the scope of this module. If so, would it be possible to provide some documentation about the possiblities and how to use them?

Alternatively, if my question seems out of scope, do you know about a module that can do such thing?
Thanks
M

**Comment by shyamrallapalli** [comment]
apologies for late reply @matthdsm 
It is currently out of scope but will think about as future improvement.

for the moment you could possibly try to use
https://github.com/jsa-aerial/JS-Binary-VCF-Tabix
